name: Daily Commit

on:
  schedule:
    # Runs every day at 09:30 UTC
    - cron: "30 9 * * *"
  workflow_dispatch: # allows manual trigger from Actions tab

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update status file - 23f3003674@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" > daily_status.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_status.txt
          git commit -m "Automated daily update [skip ci]" || echo "No changes to commit"
          git push
